// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;
export function Encrypt(arg1:string):Promise<string>;
export function Configure(arg1:Array<string>, arg2:Array<number>, arg3:string, arg4:Array<string>):Promise<void>;
